#pragma once

//==============SECTION CHUNG

#define INTRO_SCENE_ID		1
#define WORLD_MAP_SCENE_ID	2
#define PLAY_SCENE_1_1_ID	3
#define	PLAY_SCENE_1_4_ID	4

#define PRE_GET_TICK_COUNT_ORIGIN_VALUE	0
#define GET_TICK_COUNT_NORMAL_VALUE		50
#define SUB_TIME_ORIGIN_VALUE			0


#define SCORE_VALUE_100				100
#define SCORE_VALUE_10				10
#define SCORE_VALUE_1VP				900

#define SCORE_VALUE_200				200
#define SCORE_VALUE_1000				1000
#define MARIO_DEFAULT_MOVING_HORIZONTAL_REC_ID	-1
#define MARIO_CAM_PUSH_RENDER_BONUS_X		3.0f


#define GOOMBA_DIE_DIRECTION			1
#define KOOPAS_DIE_DIRECTION			1



#define MARIO_REC_TOP_ORIGIN_VALUE		0
#define MARIO_REC_BOTTOM_ORIGIN_VALUE	0
#define MARIO_REC_RIGHT_ORIGIN_VALUE	0
#define MARIO_REC_LEFT_ORIGIN_VALUE		0




//===========SECTION BACKGROUND STAGE

#define BACKGROUND_STAGE_STATE_IDLE		0
#define BACKGROUND_STAGE_STATE_DOWN		100
#define BACKGROUND_STAGE_STATE_SHAKE	200


#define BACKGROUND_STAGE_TYPE_BLACK_ANI		0	
#define BACKGROUND_STAGE_TYPE_COLOR_ANI		1
#define BACKGROUND_STAGE_TYPE_FINAL_ANI		2


#define BACKGROUND_STAGE_TYPE_BLACK		111
#define BACKGROUND_STAGE_TYPE_COLOR		222
#define BACKGROUND_STAGE_TYPE_FINAL		333

#define BACKGROUND_STAGE_TYPE_COLOR_TIME_SHOWING	4300
#define BACKGROUND_STAGE_TYPE_FINAL_TIME_SHOWING	7000
#define BACKGROUND_STAGE_TYPE_COLOR_TIME_IDLE		500
#define BACKGROUND_STAGE_STATE_SHAKE_TIME_SHAKE		700
#define	BACKGROUND_STAGE_STATE_IDLE_TIME_IDLE		1400
#define BACKGROUND_STAGE_STATE_SHAKE_TIME_SWITCHING_UP_DOWN		25
#define BACKGROUND_STAGE_STATE_SHAKE_SPEED          0.2f
#define BACKGROUND_STAGE_STATE_IDLE_SPEED_IDLE		0
#define BACKGROUND_STAGE_STATE_DOWN_SPEED			0.1f


//=============== SECTION BELL

#define BELL_BBOX_WIDTH		16
#define BELL_BBOX_HEIGHT	16

#define BELL_DIE_BBOX_WIDTH		16
#define BELL_DIE_BBOX_HEIGHT	7

#define BELL_STATE_IDLE		0
#define BELL_STATE_UP		100
#define BELL_STATE_DIE		200


#define BELL_ANI_ALIVE		0
#define BELL_ANI_DIE		1



#define BELL_STATE_DIE_TOP_BBOX		9
#define BELL_STATE_UP_TIME_UP		100
#define BELL_STATE_IDLE_SPEED_IDLE	0
#define BELL_STATE_UP_SPEED_UP		0.1f



//============SECTION BREAKABLE BRICK

#define BREAKABLE_BRICK_ANIMATION_STATE_IDLE	0
#define BREAKABLE_BRICK_ANIMATION_STATE_MOVE	100

#define BREAKABLE_BRICK_ANIMATION_GRAVITY		0.002f

#define BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_TOP			111
#define BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_TOP		222
#define BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_BOTTOM		333
#define BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_BOTTOM		444


#define BREAKABLE_BRICK_ANIMATION_MAX_PIECES			4
#define BREAKABLE_BRICK_ANIMATION_X						0
#define BREAKABLE_BRICK_ANIMATION_Y						0
#define BREAKABLE_BRICK_ANIMATION_TIME_UP				300
#define BREAKABLE_BRICK_ANIMATION_TIME_DOWN				700
#define BREAKABLE_BRICK_ANIMATION_ORIGIN_POSITION_X		12000
#define BREAKABLE_BRICK_ANIMATION_ORIGIN_POSITION_Y		12000
#define BREAKABLE_BRICK_ANIMATION_STATE_IDLE_SPEED		0
#define BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_TOP_SPEED_VX	0.04f
#define BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_TOP_SPEED_VY	0.08f
#define BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_BOTTOM_SPEED_VX	0.04f
#define BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_BOTTOM_SPEED_VY	0.04f
#define BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_TOP_SPEED_VX	0.04f
#define	BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_TOP_SPEED_VY	0.08f
#define BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_BOTTOM_SPEED_VX	0.04f
#define BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_BOTTOM_SPEED_VY	0.04f


//================== COIN

#define COIN_BBOX_WIDTH  10
#define COIN_BBOX_HEIGHT 15


#define COIN_STATE_IDLE		0
#define COIN_STATE_UP		100
#define COIN_STATE_DOWN		200

#define COIN_NORMAL			222
#define COIN_CAN_MOVE		333



#define	COIN_STATE_UP_TIME_UP		300
#define COIN_STATE_DOWN_TIME_DOWN	300

#define COIN_POSITION_SHOW_SCORE_Y		10
#define COIN_STATE_IDLE_SPEED			0
#define COIN_STATE_UP_SPEED				0.2f
#define COIN_STATE_DOWN_SPEED			0.2f


//===================FIRE BULLET
#define FIRE_BULLET_BBOX_WIDTH  9
#define FIRE_BULLET_BBOX_HEIGHT 9

#define FIRE_BULLET_FLYING_SPEED	0.1f 

#define FIRE_BULLET_STATE_FLYING		100
#define FIRE_BULLET_STATE_HIDDEN		200

#define FIRE_BULLET_ANI_RIGHT		0
#define FIRE_BULLET_ANI_LEFT		1


#define	FIRE_BULLET_ORIGIN_LIMIT		0
#define	FIRE_BULLET_BONUS_X				1
#define FIRE_BULLET_MINUS_X				1
#define FIRE_BULLET_SPEED_VX			0.1f
#define FIRE_BULLET_TIME_EXIST			5000
#define FIRE_BULLET_TIME_REMAIN_RESET	0
#define FIRE_BULLET_SPEED_VY			0.1f

#define KOOPAS_FIRE_BULLET_SHOW_MINUS_X_1		10 
#define KOOPAS_FIRE_BULLET_SHOW_MINUS_Y_1		12
#define KOOPAS_FIRE_BULLET_SHOW_MINUS_X_2		5
#define KOOPAS_FIRE_BULLET_SHOW_MINUS_Y_2		12
#define THING_ELSE_FIRE_BULLET_SHOW_MINUS_X		10
#define FIRE_BULLET_ORIGIN_POSITION				1000
#define FIRE_BULLET_STATE_HIDDEN_SPEED			0



//#======== FIRE FLOWER

#define FIRE_FLOWER_BBOX_WIDTH		16
#define FIRE_FLOWER_BBOX_HEIGHT		16

#define FIRE_FLOWER_STATE_IDLE		0
#define FIRE_FLOWER_STATE_UP		100


#define FIRE_FLOWER_STATE_UP_TIME	300		
#define	FIRE_FLOWER_ORIGIN_POSITION		7000
#define	FIRE_FLOWER_IDLE_SPEED			0
#define	FIRE_FLOWER_UP_SPEED			0.05f


//#=======FLOWER
#define FLOWER_RED_BBOX_WIDTH  16
#define FLOWER_RED_BBOX_HEIGHT 32

#define FLOWER_GREEN_BBOX_WIDTH  16
#define FLOWER_GREEN_BBOX_HEIGHT 24

#define FLOWER_GREEN_CAN_SHOOT_BBOX_WIDTH  16
#define FLOWER_GREEN_CAN_SHOOT_BBOX_HEIGHT 24

#define FLOWER_RED_ANI_LEFT			0
#define FLOWER_RED_ANI_RIGHT		1
#define FLOWER_RED_ANI_LEFT_IDLE	2
#define FLOWER_RED_ANI_RIGHT_IDLE	3
#define FLOWER_GREEN_ANI			4
#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT			5
#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT		6
#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_IDLE	7
#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_IDLE	8
#define FLOWER_RED_ANI_LEFT_UP						9
#define FLOWER_RED_ANI_RIGHT_UP						10
#define FLOWER_RED_ANI_LEFT_IDLE_UP					11
#define FLOWER_RED_ANI_RIGHT_IDLE_UP				12
#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_UP			13
#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_UP			14
#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_IDLE_UP		15
#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_IDLE_UP	16

#define FLOWER_RED				100
#define FLOWER_GREEN			200
#define FLOWER_GREEN_CAN_SHOOT  300 


#define FLOWER_RED_TOP_LIMIT			336
#define FLOWER_RED_BOT_LIMIT			384
#define TIME_SHOWING_LIMIT				3000

#define FLOWER_GREEN_TOP_LIMIT			361
#define FLOWER_GREEN_BOT_LIMIT			391
#define GREEN_TIME_SHOWING_LIMIT		2000


#define FLOWER_GREEN_CAN_SHOOT_TOP_LIMIT		344
#define FLOWER_GREEN_CAN_SHOOT_BOT_LIMIT		391


#define FLOWER_ORIGIN_SPEED					0
#define FLOWER_ALLOW_UP_DISTANCE_X			40
#define FLOWER_ALLOW_UP_DISTANCE_Y			70
#define FLOWER_TIME_SHOWING_ORIGIN_VALUE	0
#define FLOWER_SPEED_UP				0.02f
#define FLOWER_SPEED_IDLE			0
#define FLOWER_TIME_ALLOW_TO_FIRE	2900


//========FLOWER BULLET
#define FLOWER_BULLET_BBOX_WIDTH  8
#define FLOWER_BULLET_BBOX_HEIGHT 9

#define FLOWER_BULLET_X_LIMIT		72


#define FLOWER_BULLET_FLYING_SPEED		0.05f 

#define FLOWER_BULLET_STATE_FLYING		100
#define FLOWER_BULLET_STATE_HIDDEN		200

#define FLOWER_BULLET_ANI			0


#define FLOWER_BULLET_ALLOW_TO_SHOW_DISTANCE	160
#define FLOWER_BULLER_ADDTION_Y					5
#define FLOWER_IS_SHOOTING_UP_DIRECTION			1
#define FLOWER_BULLET_MINUS_X					1
#define FLOWER_BULLET_CONTROL_FLOWER_NX			1
#define FLOWER_BULLET_SPEED_VY_1				0.05f
#define FLOWER_BULLET_SPEED_VY_2				0.02f
#define FLOWER_RED_BBOX_WIDTH_ADDITION_X		2
#define FLOWER_BULLET_LIMIT_Y_1					435
#define FLOWER_BULLET_LIMIT_Y_2					165
#define FLOWER_BULLET_ORIGIN_POSITION			2000
#define FLOWER_BULLET_ORIGIN_SPEED				0


//#===== GOOMBA

#define GOOMBA_WALKING_SPEED		 0.05f
#define GOOMBA_GRAVITY				 0.002f
#define GOOMBA_DIE_DEFLECT_SPEED	 0.5f
#define GOOMBA_JUMP_SPEED			 0.35f



#define GOOMBA_NORMAL_BBOX_WIDTH			16
#define GOOMBA_NORMAL_BBOX_HEIGHT			15
#define GOOMBA_RED_FLY_BBOX_WIDTH			20
#define GOOMBA_RED_FLY_BBOX_HEIGHT			24
#define GOOMBA_RED_LOSE_WINGS_BBOX_WIDTH	20
#define GOOMBA_RED_LOSE_WINGS_BBOX_HEIGHT	19


#define GOOMBA_STATE_WALKING		100
#define GOOMBA_STATE_DIE			200
#define GOOMBA_STATE_DISAPPEAR		300
#define GOOMBA_STATE_DIE_BY_KICK	400
#define GOOMBA_STATE_RED_LOSE_WINGS 500
#define GOOMBA_STATE_IDLE			600
#define GOOMBA_STATE_GEARING		700
#define GOOMBA_STATE_FLYING			800



#define GOOMBA_NORMAL_ANI_WALKING		0
#define GOOMBA_NORMAL_ANI_DIE			1
#define GOOMBA_RED_FLY_ANI_WALKING		2
#define GOOMBA_RED_FLY_ANI_DIE			3	
#define GOOMBA_RED_FLY_ANI_LOSE_WINGS	4
#define GOOMBA_NORMAL_ANI_IDLE			5
#define GOOMBA_RED_FLY_ANI_DIE_BY_KICK	6
#define GOOMBA_NORMAL_ANI_DIE_BY_KICK	7
#define GOOMBA_RED_ANI_GEARING			8
#define GOOMBA_RED_ANI_FLYING			9

#define GOOMBA_NORMAL	888
#define GOOMBA_RED_FLY	999

#define GOOMBA_TIME_JUMPING		900

#define GOOMBA_NX						1
#define GOOMBA_STATE_DIE_BONUS_TOP		7
#define GOOMBA_STATE_WALKING_BONUS_BOTTOM	19
#define GOOMBA_STATE_RED_LOSE_WINGS_BONUS_TOP	7
#define GOOMBA_TIME_SWITCH_STATE	1000
#define GOOMBA_SWITCH_STATE_MINUS_Y		5
#define GOOMBA_STATE_GEARING_JUMPING_START  400
#define GOOMBA_JUMP_START_ORIGIN_VALUE	0
#define GOOMBA_CONTROL_JUMPTIME_FIRST	0
#define GOOMBA_CONTROL_JUMPTIME_SECOND	1
#define GOOMBA_JUMP_VY					0.2f
#define GOOMBA_FLYING_VY				0.4f
#define GOOMBA_TIME_RUNNING_INTRO_SCENE		200
#define GOOMBA_TIME_RUNNING_INTRO_SCENE_ORIGIN_VALUE 0
#define GOOMBA_DYING_TIME_ORIGIN_VALUE			0
#define GOOMBA_DYING_TIME						500
#define GOOMBA_STATE_FLYING_SWITCHING_STATE_TIME	500
#define GOOMBA_STATE_DIE_BY_KICK_VX				0.1f
#define GOOMBA_ORIGIN_SPEED						0


//#======= HIT EFFECT
#define HIT_EFFECT_STATE_IDLE	0

#define HIT_EFFECT_TURN_TAIL			100
#define HIT_EFFECT_FIRE_BULLET			200	


#define HIT_EFFECT_TURN_TAIL_ANI_RIGHT			0
#define HIT_EFFECT_TURN_TAIL_ANI_LEFT			1
#define HIT_EFFECT_ANI_FIRE_BULLET				2



#define HIT_EFFECT_TURN_TAIL_BONUS_X		5
#define HIT_EFFECT_TURN_TAIL_BONUS_Y		10
#define HIT_EFFECT_TURN_TAIL_TIME_SHOWING	250
#define HIT_EFFECT_TURN_TAIL_ORIGIN_POSITION	7000
#define TIMING_START_ORIGIN_VALUE		0

#define HIT_EFFECT_FIRE_BULLET_BONUS_X		5
#define HIT_EFFECT_FIRE_BULLET_BONUS_Y		10
#define HIT_EFFECT_FIRE_BULLET_TIME_SHOWING	250
#define HIT_EFFECT_FIRE_BULLET_ORIGIN_POSITION	6000
#define HIT_EFFECT_STATE_IDLE_SPEED			0


//#======HUD
#define HUD_TYPE_PANEL			11
#define	HUD_TYPE_WORLD			22
#define HUD_TYPE_LIFE			33
#define HUD_TYPE_TIME_PICKER	44
#define HUD_TYPE_SCORE			55
#define HUD_TYPE_MONEY			66
#define HUD_TYPE_MARIO_LUIGI	77
#define HUD_TYPE_STACK_NORMAL	88
#define HUD_TYPE_STACK_MAX		99
#define HUD_TYPE_ITEM			100
#define HUD_TYPE_BLACK_BLACK	1000

#define	HUD_TYPE_WORLD_ANI			1
#define	HUD_TYPE_MARIO_LUIGI_ANI	0
#define HUD_TYPE_PANEL_ANI			0	


#define HUD_TYPE_STACK_NORMAL_ANI_FILLED	0
#define HUD_TYPE_STACK_MAX_ANI_FILLED		1
#define HUD_TYPE_STACK_NORMAL_ANI_EMPTY		2
#define HUD_TYPE_STACK_MAX_ANI_EMPTY		3


#define HUD_TYPE_ITEM_ANI_EMPTY				0	
#define HUD_TYPE_ITEM_ANI_MUSHROOM			1	
#define HUD_TYPE_ITEM_ANI_FLOWER			2	
#define HUD_TYPE_ITEM_ANI_STAR				3

#define TIMING_RENDER_ITEM_TIME				200
#define TIMING_RENDER_ITEM_TIME_ORIGIN_VALUE	0


//#============INTRO SCENE


#define SIT_DOWN_COUNT_TIME			200
#define TIME_COUNT_TIME_1				1800
#define TIME_COUNT_TIME_2				2000
#define RED_SMALL_COUNT_TIME			3500
#define TIME_COUNT_TIME_3               2950
#define TIME_COUNT_TIME_4				4000
#define HITTED_START_TIME				350
#define MARIO_STATE_LOOK_UP_TIME		700
#define MARIO_STATE_WALKING_RIGHT_TIME	2200
#define PLAYER2_LIMIT_X					320
#define PLAYER2_NX						1
#define GREEN_IDLE_COUNT_1				600
#define GREEN_IDLE_COUNT_2              900
#define RED_JUMP_COUNT_1                850
#define RED_JUMP_COUNT_2				1400
#define RED_JUMP_COUNT_3				1800
#define RED_JUMP_COUNT_4				2000
#define RED_JUMP_COUNT_5				2600
#define RED_JUMP_COUNT_6				3000
#define GREEN_RUN_AWAY_COUNT_TIME		400
#define RED_SMALL_COUNT_TIME_2			300
#define RED_SMALL_COUNT_TIME_3			700
#define RED_SMALL_COUNT_TIME_4			1500
#define RED_SMALL_COUNT_TIME_5			1900
#define RED_SMALL_COUNT_TIME_6			2100
#define RED_SMALL_COUNT_TIME_7			2800
#define RED_SMALL_COUNT_TIME_8			3200
#define RED_SMALL_COUNT_TIME_9			4000
#define RED_SMALL_COUNT_TIME_10			6000
#define RED_SMALL_COUNT_TIME_11			10200


#define INTRO_SCENE_OBJECT_TYPE_MARIO_RED				0
#define INTRO_SCENE_OBJECT_TYPE_BRICK					1
#define INTRO_SCENE_OBJECT_TYPE_GOOMBA_NORMAL			2
#define INTRO_SCENE_OBJECT_TYPE_KOOPAS_BLACK			3
#define INTRO_SCENE_OBJECT_TYPE_NO_COLLISION_OBJECTS_NUMBER_THREE	4
#define INTRO_SCENE_OBJECT_TYPE_STAR					5
#define INTRO_SCENE_OBJECT_TYPE_BACKGROUND_STAGE_BLACK	6
#define INTRO_SCENE_OBJECT_TYPE_LEAF					7
#define INTRO_SCENE_OBJECT_TYPE_MUSHROOM_RED			8
#define INTRO_SCENE_OBJECT_TYPE_MENU_GAME				9
#define INTRO_SCENE_OBJECT_TYPE_MARIO_GREEN				10
#define INTRO_SCENE_OBJECT_TYPE_SCROLLING_STAGE			12
#define INTRO_SCENE_OBJECT_TYPE_BACKGROUND_STAGE_COLOR	13
#define INTRO_SCENE_OBJECT_TYPE_BACKGROUND_STAGE_FINAL	14
#define INTRO_SCENE_OBJECT_TYPE_KOOPAS_XANH				15
#define INTRO_SCENE_OBJECT_TYPE_NO_COLLISION_OBJECTS_BUSH	16
#define INTRO_SCENE_OBJECT_TYPE_KOOPAS_LINE				17
#define INTRO_SCENE_OBJECT_TYPE_KOOPAS_FASTER			18





#define MARIO_TIME_COUNT  1000




//#============== KOOPAS

#define KOOPAS_WALKING_SPEED	 0.02f
#define KOOPAS_GRAVITY			 0.002f
#define KOOPAS_DIE_DEFLECT_SPEED 0.5f
#define KOOPAS_SHELL_DEFLECT_SPEED 0.4f
#define KOOPAS_BBOX_WIDTH		 16
#define KOOPAS_BBOX_HEIGHT		 26
#define KOOPAS_BBOX_HEIGHT_SHELL 16
#define KOOPAS_BBOX_HEIGHT_DIE	 16

#define KOOPAS_STATE_WALKING	100
#define KOOPAS_STATE_SHELL		200
#define KOOPAS_STATE_DIE		300
#define KOOPAS_STATE_SPINNING	400
#define KOOPAS_STATE_HOLDING	500
#define KOOPAS_STATE_WALKING_RIGHT			600
#define KOOPAS_STATE_WALKING_RIGHT_FASTER	700
#define KOOPAS_STATE_FLYING_UP_DOWN			800


#define KOOPAS_XANH_ANI_WALKING_LEFT  0
#define KOOPAS_XANH_ANI_WALKING_RIGHT 1
#define KOOPAS_XANH_ANI_FLYING_LEFT   2
#define KOOPAS_XANH_MAI_ANI_UP		  3
#define KOOPAS_XANH_MAI_ANI_NGUA	  4	
#define KOOPAS_RED_ANI_WALKING_LEFT   5
#define KOOPAS_RED_ANI_WALKING_RIGHT  6
#define KOOPAS_RED_ANI_FLYING_LEFT	  7
#define KOOPAS_RED_MAI_ANI_UP		  8
#define KOOPAS_XANH_MAI_ANI_SPINNING  9
#define KOOPAS_RED_MAI_ANI_SPINNING	  10
#define KOOPAS_XANH_ANI_REVIVING	  11	
#define KOOPAS_RED_ANI_REVIVING		  12
#define KOOPAS_RED_MAI_ANI_NGUA		  13
#define KOOPAS_XANH_ANI_REVIVING_NGUA			14
#define KOOPAS_RED_ANI_REVIVING_NGUA			15
#define KOOPAS_BLACK_UP							16
#define KOOPAS_BLACK_NGUA						17
#define KOOPAS_XANH_ANI_WALKING_RIGHT_FASTER	18
#define KOOPAS_XANH_MAI_ANI_SPINNING_NGUA		19
#define KOOPAS_RED_MAI_ANI_SPINNING_NGUA		20
#define KOOPAS_RED_ANI_FLYING_LEFT_NEW			21

#define KOOPAS_JUMP_SPEED		0.35f
#define KOOPAS_TIME_JUMPING		900


#define KOOPAS_XANH_WALK	111
#define KOOPAS_XANH_FLY		222
#define KOOPAS_RED_WALK		333
#define KOOPAS_BLACK		444
#define KOOPAS_RED_FLY		777

#define KOOPAS_TYPE_LINE	555
#define KOOPAS_TYPE_FASTER	666
#define KOOPAS_NX			1
#define KOOPAS_SHELL_DIRECTION	1
#define KOOPAS_SHELL_VX			0.1f
#define KOOPAS_JUMP_SPEED_VX	1.5f
#define SWITCHING_STATE_TIME	2000
#define SWITCHING_STATE_TIME_ORIGIN_VALUE	0
#define KOOPAS_STATE_FLYING_UP_DOWN_VY		0.06f
#define KOOPAS_SHELL_DEFLECT_SPEED_VX		0.04f
#define REVIVE_START_TIME			5000
#define REVIVE_START_X				5
#define REVIVE_START_Y				10
#define REVIVE_START_TIME_2			3000
#define KOOPAS_SET_POSITION			21000
#define KOOPAS_IS_HOLDING_X			1
#define KOOPAS_IS_HOLDING_Y			10
#define KOOPAS_IS_HOLDING_Y_2		8
#define MARIO_LEVEL_SMALL_KOOPAS_BONUS_Y	10
#define MARIO_LEVEL_TAIL_KOOPAS_BONUS_X		15
#define KOOPAS_CHECK_POSITION_RECOG			1.0f
#define KOOPAS_CHECK_POSITION_MINUS_Y		5.0f
#define KOOPAS_CHECK_POSITION_BONUS_X		12.0f
#define KOOPAS_BLACK_JUMP_VY_1				0.4f
#define KOOPAS_BLACK_JUMP_VY_2				0.15f
#define MARIO_STATE_HITTED_KOOPAS_VX		0.2f
#define MARIO_STATE_HITTED_KOOPAS_VY		0.1f
#define KOOPAS_RESET_SPINNING_LIMIT_X			315
#define KOOPAS_RESET_SPINNING_SET_POSITION_X	30
#define KOOPAS_RESET_SPINNING_SET_POSITION_Y	117
#define KOOPAS_STATE_DIE_VX				0.1f
#define KOOPAS_STATE_SHELL_IDLE_SPEED			0



//#==== LEAF
#define LEAF_BBOX_WIDTH		16
#define LEAF_BBOX_HEIGHT	14

#define LEAF_STATE_IDLE		0
#define LEAF_STATE_UP		100
#define LEAF_STATE_DOWN		200



#define LEAF_ANI_LEFT		0
#define LEAF_ANI_RIGHT		1


#define COLLI_TIME_TAIL_ORIGIN_VALUE	0
#define LEAF_UPPING_START_TIME_1		500
#define	LEAF_UPPING_START_TIME_2		1500
#define LEAF_DOWNING_START_TIME_ORIGIN_VALUE	0
#define LEAF_DOWNING_START_TIME		500
#define LEAF_SET_POSITION			5000
#define COLLI_TIME_TAIL				400
#define LEAF_STATE_IDLE_SPEED		0				
#define LEAF_STATE_UP_SPEED			0.04f
#define LEAF_STATE_DOWN_VX          0.04f
#define LEAF_STATE_DOWN_VY			0.035f

//#=============MARIO


#define MARIO_WALKING_SPEED		0.2f 
#define MARIO_ACCELERATION		0.008f
#define MARIO_RUNNING_SPEED		0.056f 
#define MARIO_SPEED_DOWN		0.01f 

#define MARIO_JUMP_SPEED_Y		0.5f
#define MARIO_JUMP_DEFLECT_SPEED 0.2f
#define MARIO_GRAVITY			0.002f
#define MARIO_DIE_DEFLECT_SPEED	 0.4f

#define MARIO_STATE_IDLE			0
#define MARIO_STATE_WALKING_RIGHT	100
#define MARIO_STATE_WALKING_LEFT	200
#define MARIO_STATE_JUMP			300
#define MARIO_STATE_DIE				400
#define MARIO_STATE_FLYING_RIGHT	500
#define MARIO_STATE_FLYING_LEFT		600
#define MARIO_STATE_BRAKING_RIGHT	700	
#define MARIO_STATE_BRAKING_LEFT	800
#define MARIO_STATE_HOLDING_RIGHT	900
#define MARIO_STATE_HOLDING_LEFT	1000
#define MARIO_STATE_HOLDING			1100
#define MARIO_STATE_KICK			1200
#define MARIO_STATE_RUNNING_RIGHT	1300
#define MARIO_STATE_RUNNING_LEFT	1400
#define MARIO_STATE_SITDOWN			1500
#define MARIO_STATE_TURNING_TAIL	1600
#define MARIO_STATE_SPEED_DOWN		1700
#define MARIO_STATE_FALLING_DOWN	1800
#define MARIO_STATE_JUMP_HIGH		1900
#define MARIO_STATE_HITTED			2000
#define MARIO_STATE_LOOK_UP			2100
#define MARIO_STATE_PIPE_DOWNING	2200
#define MARIO_STATE_PIPE_UPPING		2300
#define MARIO_STATE_JUMPING_LONGER	2400


#define MARIO_ANI_BIG_IDLE_RIGHT		0
#define MARIO_ANI_BIG_IDLE_LEFT			1
#define MARIO_ANI_BIG_WALKING_RIGHT		2	
#define MARIO_ANI_BIG_WALKING_LEFT		3
#define MARIO_ANI_BIG_JUMPING_RIGHT		4
#define MARIO_ANI_BIG_JUMPING_LEFT		5
#define MARIO_ANI_BIG_FLYING_RIGHT		6	
#define MARIO_ANI_BIG_FLYING_LEFT		7
#define MARIO_ANI_BIG_BRAKING_RIGHT		8	
#define MARIO_ANI_BIG_BRAKING_LEFT		9
#define MARIO_ANI_BIG_HOLDING_RIGHT		10	
#define MARIO_ANI_BIG_HOLDING_LEFT		11
#define MARIO_ANI_BIG_KICKING_RIGHT		12	
#define MARIO_ANI_BIG_KICKING_LEFT		13
#define MARIO_ANI_BIG_RUNNING_RIGHT		14	
#define MARIO_ANI_BIG_RUNNING_LEFT		15
#define MARIO_ANI_BIG_SITDOWN_RIGHT		16	
#define MARIO_ANI_BIG_SITDOWN_LEFT		17
#define MARIO_ANI_BIG_JUMP_FALL_RIGHT	18	
#define MARIO_ANI_BIG_JUMP_FALL_LEFT	19

#define MARIO_ANI_SMALL_IDLE_RIGHT			20
#define MARIO_ANI_SMALL_IDLE_LEFT			21
#define MARIO_ANI_SMALL_WALKING_RIGHT		22	
#define MARIO_ANI_SMALL_WALKING_LEFT		23
#define MARIO_ANI_SMALL_JUMPING_RIGHT		24
#define MARIO_ANI_SMALL_JUMPING_LEFT		25
#define MARIO_ANI_SMALL_FLYING_RIGHT		26	
#define MARIO_ANI_SMALL_FLYING_LEFT			27
#define MARIO_ANI_SMALL_BRAKING_RIGHT		28	
#define MARIO_ANI_SMALL_BRAKING_LEFT		29
#define MARIO_ANI_SMALL_HOLDING_RIGHT		30	
#define MARIO_ANI_SMALL_HOLDING_LEFT		31
#define MARIO_ANI_SMALL_KICKING_RIGHT		32	
#define MARIO_ANI_SMALL_KICKING_LEFT		33
#define MARIO_ANI_SMALL_RUNNING_RIGHT		34	
#define MARIO_ANI_SMALL_RUNNING_LEFT		35



#define MARIO_ANI_TAIL_IDLE_RIGHT		40
#define MARIO_ANI_TAIL_IDLE_LEFT		41
#define MARIO_ANI_TAIL_WALKING_RIGHT	42	
#define MARIO_ANI_TAIL_WALKING_LEFT		43        
#define MARIO_ANI_TAIL_JUMPING_RIGHT	44
#define MARIO_ANI_TAIL_JUMPING_LEFT		45
#define MARIO_ANI_TAIL_FLYING_RIGHT		46	
#define MARIO_ANI_TAIL_FLYING_LEFT		47
#define MARIO_ANI_TAIL_BRAKING_RIGHT	48	
#define MARIO_ANI_TAIL_BRAKING_LEFT		49
#define MARIO_ANI_TAIL_HOLDING_RIGHT	50	
#define MARIO_ANI_TAIL_HOLDING_LEFT		51
#define MARIO_ANI_TAIL_KICKING_RIGHT	52	
#define MARIO_ANI_TAIL_KICKING_LEFT		53
#define MARIO_ANI_TAIL_RUNNING_RIGHT	54	
#define MARIO_ANI_TAIL_RUNNING_LEFT		55
#define MARIO_ANI_TAIL_SITDOWN_RIGHT	56
#define MARIO_ANI_TAIL_SITDOWN_LEFT		57
#define MARIO_ANI_TAIL_TURNING_RIGHT	58	
#define MARIO_ANI_TAIL_TURNING_LEFT		59
#define MARIO_ANI_TAIL_JUMP_FALL_RIGHT	60	
#define MARIO_ANI_TAIL_JUMP_FALL_LEFT	61

#define MARIO_ANI_FIRE_IDLE_RIGHT		62
#define MARIO_ANI_FIRE_IDLE_LEFT		63
#define MARIO_ANI_FIRE_WALKING_RIGHT	64	
#define MARIO_ANI_FIRE_WALKING_LEFT		65
#define MARIO_ANI_FIRE_JUMPING_RIGHT	66
#define MARIO_ANI_FIRE_JUMPING_LEFT		67
#define MARIO_ANI_FIRE_FLYING_RIGHT		68	
#define MARIO_ANI_FIRE_FLYING_LEFT		69
#define MARIO_ANI_FIRE_BRAKING_RIGHT	70	
#define MARIO_ANI_FIRE_BRAKING_LEFT		71
#define MARIO_ANI_FIRE_HOLDING_RIGHT	72
#define MARIO_ANI_FIRE_HOLDING_LEFT		73
#define MARIO_ANI_FIRE_KICKING_RIGHT	74	
#define MARIO_ANI_FIRE_KICKING_LEFT		75
#define MARIO_ANI_FIRE_RUNNING_RIGHT	76	
#define MARIO_ANI_FIRE_RUNNING_LEFT		77
#define MARIO_ANI_FIRE_SITDOWN_RIGHT	78
#define MARIO_ANI_FIRE_SITDOWN_LEFT		79
#define MARIO_ANI_FIRE_SHOOTING_RIGHT	80	
#define MARIO_ANI_FIRE_SHOOTING_LEFT	81
#define MARIO_ANI_BIG_MAX_SPEED_RIGHT	82
#define MARIO_ANI_BIG_MAX_SPEED_LEFT	83
#define MARIO_ANI_FIRE_MAX_SPEED_RIGHT	84
#define MARIO_ANI_FIRE_MAX_SPEED_LEFT	85
#define MARIO_ANI_SMALL_MAX_SPEED_RIGHT	86
#define MARIO_ANI_SMALL_MAX_SPEED_LEFT	87
#define MARIO_ANI_TAIL_MAX_SPEED_RIGHT	88
#define MARIO_ANI_TAIL_MAX_SPEED_LEFT	89
#define	MARIO_ANI_FALLING_LEFT			90
#define MARIO_ANI_FALLING_RIGHT			91
#define	MARIO_ANI_FIRE_JUMP_FALL_RIGHT	92
#define MARIO_ANI_FIRE_JUMP_FALL_LEFT	93

#define MARIO_ANI_BIG_IDLE_HOLDING_RIGHT		94	
#define MARIO_ANI_BIG_IDLE_HOLDING_LEFT			95
#define MARIO_ANI_SMALL_IDLE_HOLDING_RIGHT		96	
#define MARIO_ANI_SMALL_IDLE_HOLDING_LEFT		97
#define MARIO_ANI_TAIL_IDLE_HOLDING_RIGHT		98	
#define MARIO_ANI_TAIL_IDLE_HOLDING_LEFT		99
#define MARIO_ANI_FIRE_IDLE_HOLDING_RIGHT		100	
#define MARIO_ANI_FIRE_IDLE_HOLDING_LEFT		101


#define MARIO_GREEN_ANI_BIG_IDLE_RIGHT			102
#define MARIO_GREEN_ANI_BIG_IDLE_LEFT			103
#define MARIO_GREEN_ANI_BIG_WALKING_RIGHT		104
#define MARIO_GREEN_ANI_BIG_WALKING_LEFT		105
#define MARIO_GREEN_ANI_BIG_JUMPING_RIGHT		106
#define MARIO_GREEN_ANI_BIG_JUMPING_LEFT		107
#define MARIO_GREEN_ANI_BIG_HOLDING_IDLE_RIGHT	108
#define MARIO_GREEN_ANI_BIG_HOLDING_IDLE_LEFT	109
#define MARIO_GREEN_ANI_BIG_HOLDING_RIGHT		110
#define MARIO_GREEN_ANI_BIG_HOLDING_LEFT		111
#define MARIO_GREEN_ANI_BIG_KICKING_RIGHT		112
#define MARIO_GREEN_ANI_BIG_KICKING_LEFT		113
#define MARIO_GREEN_ANI_JUMP_FALL_RIGHT			114
#define MARIO_GREEN_ANI_JUMP_FALL_LEFT			115
#define MARIO_GREEN_ANI_BIG_RUNNING_RIGHT		116
#define MARIO_GREEN_ANI_BIG_RUNNING_LEFT		117

#define MARIO_RED_ANI_HITTED					118
#define MARIO_RED_LOOKING_UP					119

#define MARIO_ANI_DIE							120

#define MARIO_ANI_BIG_PIPE						121
#define MARIO_ANI_SMALL_PIPE					122
#define MARIO_ANI_TAIL_PIPE						123
#define MARIO_ANI_FIRE_PIPE						124

#define MARIO_TRANSFORM_LEFT					125
#define MARIO_TRANSFORM_RIGHT					126

#define MARIO_SMOKE_TRANSFORM_LEFT				127
#define MARIO_SMOKE_TRANSFORM_RIGHT				128

#define MARIO_ANI_BIG_JUMP_MAX_POWER_RIGHT			129
#define MARIO_ANI_BIG_JUMP_MAX_POWER_LEFT			130
#define MARIO_ANI_SMALL_JUMP_MAX_POWER_RIGHT		131
#define MARIO_ANI_SMALL_JUMP_MAX_POWER_LEFT		    132
#define MARIO_ANI_TAIL_JUMP_MAX_POWER_RIGHT			133
#define MARIO_ANI_TAIL_JUMP_MAX_POWER_LEFT			134
#define MARIO_ANI_FIRE_JUMP_MAX_POWER_RIGHT			135
#define MARIO_ANI_FIRE_JUMP_MAX_POWER_LEFT			136

#define MARIO_FIRE_TRANSFORM_RIGHT					137
#define MARIO_FIRE_TRANSFORM_LEFT					138


#define	MARIO_LEVEL_BIG		2
#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_TAIL	3
#define	MARIO_LEVEL_FIRE	4

#define MARIO_BIG_BBOX_WIDTH  15
#define MARIO_BIG_BBOX_HEIGHT 27

#define MARIO_SMALL_BBOX_WIDTH  13
#define MARIO_SMALL_BBOX_HEIGHT 15

#define MARIO_TAIL_BBOX_WIDTH  15 
#define MARIO_TAIL_BBOX_HEIGHT 27

#define MARIO_FIRE_BBOX_WIDTH  14
#define MARIO_FIRE_BBOX_HEIGHT 27

#define MARIO_UNTOUCHABLE_TIME	 3000
#define MARIO_TURNING_TIME		 400
#define MARIO_FIRING_RECOG_TIME	 100	 
#define MARIO_KICKING_TIME		 200	
#define MARIO_FIRING_TIME		 400	
#define MARIO_RUNNING_LIMIT_TIME 300
#define MARIO_FLYING_LIMIT_TIME	 7000
#define MARIO_TURNING_BONUS_HEIGHT	8

#define MARIO_TYPE_RED			1
#define MARIO_TYPE_GREEN		2

#define MARIO_MAX_STACK			 7	


#define MARIO_DIFFERENCE_HEIGHT 12

#define MARIO_LIMIT_Y_DIE		750
#define SWITCH_SCENE_START_TIME	2000
#define SAVE_NODE_ID_DIE		0
#define SWITCH_SCENE_START_TIME_2	1500
#define SWITCH_SCENE_START_TIME_3	3000
#define COUNT_DOWN_TIME_START_TIME	50
#define COUNT_DOWN_TIME_START_ORIGIN_VALUE	0
#define SWITCH_SCENE_START_TIME_4	5500
#define	SCORE_UP_COUNT_DOWN			50
#define SWITCH_SCENE_START_TIME_5	8000
#define SAVE_NODE_ID_PASS_1_4		8
#define SAVE_NODE_ID_PASS_1_1		2
#define TURNING_START_TIME			200
#define MARIO_TOP_REC_BONUS			15
#define MARIO_BOTTOM_REC_BONUS		8
#define MARIO_LEFT_REC_BONUS		9
#define MARIO_RIGHT_REC_BONUS		25
#define UNTOUCHABLE_FLASHING_TIME	50
#define TIME_MARIO_ORIGIN_VALUE		0
#define MARIO_FLYING_START_ORIGIN_VALUE	0
#define TIME_LOSE_STACK_TIME_1		3000
#define TIME_LOSE_STACK_TIME_2		3700
#define TIME_SUB_STACK_FASTER		50
#define IS_TRANSFORMING_VX			0
#define IS_JUMPING_CHECK_POSITION	1.0f
#define PIPE_DOWNING_START_TIME_1	2500
#define PIPE_DOWNING_START_TIME_2	5000
#define PIPE_UPPING_START_TIME_1	3500
#define PIPE_UPPING_START_TIME_2	6500
#define PIPE_UPPING_START_TIME_3	5500
#define PIPE_UPPING_START_TIME_4	4500
#define PIPE_UPPING_START_TIME_5	3500
#define TRANSFORMING_START_TIME		1000
#define TRANSFORMING_IDLE_SPEED		0
#define TIMING_JUMPING_LONGER		100
#define JUMPING_LONGER_SPEED		0.4f
#define PIPE_TYPE_DOWN_CONTROL_X_LEFT	2
#define PIPE_TYPE_DOWN_CONTROL_X_RIGHT	16
#define PIPE_TYPE_UP_CONTROL_X_LEFT	2
#define PIPE_TYPE_UP_CONTROL_X_RIGHT	16
#define MARIO_JUMP_DEFLECT_SPEED_BONUS	2.5f
#define MARIO_JUMP_DEFLECT_SPEED_BONUS_2	1.5f
#define MARIO_JUMP_ON_KOOPAS_BONUS_VX		0.3f
#define KOOPAS_MAX_POINT_PARA				8
#define MARIO_SCORE_UP_50					50
#define MARIO_NX			1
#define MARIO_STATE_WALKING_SPEED		0.15f
#define MARIO_ORIGIN_SPEED				0
#define MARIO_BONUS_ACCELERATION_SPEED	5
#define MARIO_STATE_JUMP_LOWER_SPEED	0.4f
#define MARIO_STATE_JUMP_HIGH_SPEED		0.77f
#define MARIO_STATE_PIPE_UPPING_SPEED	0.01f
#define MARIO_STATE_PIPE_DOWNING_SPEED  0.01f
#define MARIO_CONFIG_BBOX_TOP			9.0f
#define SET_LEVEL_BONUS_X				2.0f



//#=============MOVING HORIZONTAL RECTANGLE

#define MOVING_HORIZONTAL_RECTANGLE_BBOX_WIDTH		48
#define MOVING_HORIZONTAL_RECTANGLE_BBOX_HEIGHT		16



#define  MOVING_HORIZONTAL_RECTANGLE_STATE_NORMAL		0
#define  MOVING_HORIZONTAL_RECTANGLE_STATE_DOWN			100

#define	 MOVING_HORIZONTAL_RECTANGLE_STATE_NORMAL_SPEED   -0.05f
#define  MOVING_HORIZONTAL_RECTANGLE_STATE_DOWN_SPEED	   0.04f

#define  MOVING_HORIZONTAL_RECTANGLE_BONUS_Y_1		27
#define	 MOVING_HORIZONTAL_RECTANGLE_BONUS_Y_2		15
#define MOVING_HORIZONTAL_RECTANGLE_ORIGIN_SPEED	0


//#============ MUSHROOM
#define MUSHROOM_BBOX_WIDTH		16
#define MUSHROOM_BBOX_HEIGHT	16

#define MUSHROOM_STATE_IDLE		0
#define MUSHROOM_STATE_UP		100
#define MUSHROOM_STATE_MOVE		200
#define MUSHROOM_STATE_MOVE_LEFT 300

#define MUSHROOM_GRAVITY		0.002f
#define MUSHROOM_RED			567
#define MUSHROOM_GREEN			678

#define MUSHROOM_ANI_RED		0
#define MUSHROOM_ANI_GREEN		1

#define MUSHROOM_MOVE_DIRECTION	1
#define MUSHROOM_UPPING_START	300
#define MUSHROOM_SET_POSITION	6000
#define MUSHROOM_STATE_IDLE_SPEED	0
#define MUSHROOM_STATE_MOVE_SPEED	0.04f
#define MUSHROOM_STATE_MOVE_LEFT_SPEED	0.04f
#define MUSHROOM_STATE_UP_SPEED		0.08f


//#====== NODE
#define NODE_FIND_DISTANCE		50


//#====== PIPE
#define PIPE_BBOX_WIDTH  32
#define PIPE_BBOX_HEIGHT 16

#define PIPE_BBOX_WIDTH_NORMAL	16


#define PIPE_TYPE_NORMAL	100
#define PIPE_TYPE_DOWN		200
#define PIPE_TYPE_UP		300

//#======= PLAYSCENE 

#define TUNNEL_CAM_Y	980

#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6
#define SCENE_SECTION_MAP				7
#define SCENE_SECTION_GRID				8

#define OBJECT_TYPE_MARIO				 0
#define OBJECT_TYPE_BRICK				 1
#define OBJECT_TYPE_GOOMBA_NORMAL		 2
#define OBJECT_TYPE_KOOPAS_XANH_WALK	 3
#define OBJECT_TYPE_NO_COLLISION_OBJECTS 4
#define OBJECT_TYPE_RECTANGLE			 5
#define OBJECT_TYPE_PIPE_NORMAL			 6
#define OBJECT_TYPE_KOOPAS_XANH_BAY		 7 
#define OBJECT_TYPE_KOOPAS_RED_WALK		 8
#define OBJECT_TYPE_COIN_NORMAL			 10
#define OBJECT_TYPE_GOOMBA_RED_FLY  11 
#define OBJECT_TYPE_FIRE_BULLET		12
#define OBJECT_TYPE_FLOWER_RED		13
#define OBJECT_TYPE_FLOWER_BULLET	14
#define OBJECT_TYPE_COIN_CAN_MOVE	15
#define OBJECT_TYPE_LEAF			16
#define OBJECT_TYPE_MUSHROOM_RED		17
#define OBJECT_TYPE_QUESTION_BRICK_HAVE_LEAF	18
#define OBJECT_TYPE_MUSHROOM_GREEN		19
#define OBJECT_TYPE_QUESTION_BRICK_JUST_HAVE_MUSHROOM	20
#define OBJECT_TYPE_FLOWER_GREEN				21
#define OBJECT_TYPE_FLOWER_GREEN_CAN_SHOOT		22
#define OBJECT_TYPE_BREAKABLE_BRICK				23
#define OBJECT_TYPE_BELL						24

#define OBJECT_TYPE_HUD_PANEL			25
#define OBJECT_TYPE_MARIO_LUIGI			26
#define OBJECT_TYPE_LIFE				27
#define OBJECT_TYPE_MONEY				28
#define OBJECT_TYPE_SCORE				29
#define OBJECT_TYPE_TIME_PICKER			30
#define OBJECT_TYPE_WORLD				31
#define OBJECT_TYPE_STACK_NORMAL		32
#define OBJECT_TYPE_STACK_MAX			33
#define OBJECT_TYPE_ITEM				34

#define OBJECT_TYPE_BLACK_BLACK			35
#define OBJECT_TYPE_SPECIAL_ITEM		36

#define OBJECT_TYPE_PIPE_DOWN			37
#define OBJECT_TYPE_PIPE_UP				38
#define OBJECT_TYPE_SCORE_AND_1LV		39

#define OBJECT_TYPE_WORDS_END_SCENE_COURSE_CLEAR		40
#define OBJECT_TYPE_WORDS_END_SCENE_YOU_GOT_A_CARD		41
#define OBJECT_TYPE_WORDS_END_SCENE_ITEM				42

#define OBJECT_TYPE_BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_TOP				43
#define OBJECT_TYPE_BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_TOP			44
#define OBJECT_TYPE_BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_BOTTOM			45
#define OBJECT_TYPE_BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_BOTTOM			46

#define OBJECT_TYPE_NEW_MAP_CAM											47
#define OBJECT_TYPE_QUESTION_BRICK_HAVE_MULTIPLE_LIFE					48
#define OBJECT_TYPE_MOVING_HORIZONTAL_RECTANGLE							49

#define OBJECT_TYPE_BOOMERANG											50
#define OBJECT_TYPE_BOOMERANG_ENEMY										51

#define OBJECT_TYPE_KOOPAS_RED_FLY										52

#define OBJECT_TYPE_FIRE_FLOWER											53

#define OBJECT_TYPE_HIT_EFFECT_TURN_TAIL								54

#define OBJECT_TYPE_HIT_EFFECT_FIRE_BULLET								55


#define OBJECT_TYPE_PORTAL												56

#define CAM_X_BONUS	50

#define MAX_SCENE_LINE 1024


#define MAX_RENDER_LAYER		4


#define IN_USE_WIDTH		330
#define IN_USE_HEIGHT		300


#define GRID_SECTION_SETTINGS	1
#define GRID_SECTION_OBJECTS	2

#define MOVE_CAM_X_VX		0.1f



#define GRID_SECTION_SETTINGS	1
#define GRID_SECTION_OBJECTS	2
#define MAX_GRID_LINE 1024

#define CAM_STATE_ORIGIN		1
#define CAM_STATE_2				2



//#=========== PORTAL
#define PORTAL_WIDTH	32
#define PORTAL_HEIGHT	10


//#======= QUESTION BRICK
#define QUESTION_BRICK_BBOX_WIDTH  16
#define QUESTION_BRICK_BBOX_HEIGHT 16



#define QUESTION_BRICK_ANI_ALIVE	0
#define QUESTION_BRICK_ANI_DEAD		1
#define QUESTION_BRICK_ANI_NEW_TYPE	2


#define QUESTION_BRICK_HAVE_LEAF			777
#define QUESTION_BRICK_JUST_HAVE_MUSHROOM	888
#define QUESTION_BRICK_HAVE_COIN_MULTIPLE_LIFE	999
#define QUESTION_BRICK_HAVE_COIN_MULTIPLE_LIFE_NUMBER_OF_LIFES	10
#define QUESTION_BRICK_NORMAL_LIFE				0
#define QUESTION_BRICK_TIME_UPS					4
#define QUESTION_BRICK_MINUS_Y_UP				2
#define QUESTION_BRICK_BONUS_Y_UP				2
#define QUESTION_BRICK_ORIGIN_SPEED				0
#define QUESTION_BRICK_TIME_Y_UP_ORIGIN			0



//#==== SCORE 

#define SCORE_STATE_IDLE	0
#define SCORE_STATE_UP		100


#define SCORE_TYPE_100			100
#define SCORE_TYPE_200			200	
#define SCORE_TYPE_400			400
#define SCORE_TYPE_800			800
#define SCORE_TYPE_1000			1000
#define SCORE_TYPE_2000			2000
#define SCORE_TYPE_4000			4000
#define SCORE_TYPE_8000			8000
#define SCORE_TYPE_1LIFE		900




#define SCORE_100_ANI			0
#define SCORE_200_ANI			1	
#define SCORE_400_ANI			2
#define SCORE_800_ANI			3
#define SCORE_1000_ANI			4
#define SCORE_2000_ANI			5
#define SCORE_4000_ANI			6
#define SCORE_8000_ANI			7
#define SCORE_1LIFE_ANI			8

#define SCORE_MARIO_SHOW_POINT_X	5
#define SCORE_MARIO_SHOW_POINT_Y	10
#define SCORE_STATE_UP_TIMING_START	600
#define SCORE_SET_POSITION			6000
#define SCORE_STATE_IDLE_SPEED		0
#define SCORE_STATE_UP_SPEED       0.08f

//#=============== SCROLLING STAGE

#define SCROLLING_STAGE_STATE_IDLE		0
#define SCROLLING_STAGE_STATE_UP		100
#define SCROLLING_STAGE_STATE_UP_TIME_SHOWING	1000
#define SCROLLING_STAGE_STATE_IDLE_SPEED	0
#define SCROLLING_STAGE_STATE_UP_SPEED	0.1f

//#================= SPECIAL ITEM
#define SPECIAL_ITEM_BBOX_WIDTH		16
#define SPECIAL_ITEM_BBOX_HEIGHT	16

#define SPECIAL_ITEM_STATE_FLOWER_IDLE			100
#define SPECIAL_ITEM_STATE_MUSHROOM_IDLE		200
#define SPECIAL_ITEM_STATE_STAR_IDLE			300

#define SPECIAL_ITEM_STATE_FLOWER_UP			400
#define SPECIAL_ITEM_STATE_MUSHROOM_UP			500
#define SPECIAL_ITEM_STATE_STAR_UP				600

#define SPECIAL_ITEM_STATE_FLOWER_IDLE_ANI			0
#define SPECIAL_ITEM_STATE_MUSHROOM_IDLE_ANI		1
#define SPECIAL_ITEM_STATE_STAR_IDLE_ANI			2

#define SPECIAL_ITEM_STATE_FLOWER_UP_ANI			3
#define SPECIAL_ITEM_STATE_MUSHROOM_UP_ANI			4
#define SPECIAL_ITEM_STATE_STAR_UP_ANI				5


#define SPECIAL_ITEM_UPPING_START			1400
#define SPECIAL_ITEM_SWITCHING_STATE_START	250
#define SPECIAL_ITEM_STATE_IDLE_SPEED			0
#define SPECIAL_ITEM_STATE_UP_SPEED				0.09f



//#================ WORDS END SCENE
#define WORDS_END_SCENE_TYPE_COURSE_CLEAR_ANI		0
#define WORDS_END_SCENE_TYPE_YOU_GOT_A_CARD_ANI		1
#define WORDS_END_SCENE_TYPE_ITEM_ANI_MUSHROOM		2
#define WORDS_END_SCENE_TYPE_ITEM_ANI_FLOWER		3
#define WORDS_END_SCENE_TYPE_ITEM_ANI_STAR			4


#define WORDS_END_SCENE_TYPE_COURSE_CLEAR		111
#define WORDS_END_SCENE_TYPE_YOU_GOT_A_CARD		222
#define WORDS_END_SCENE_TYPE_ITEM				333

#define WORDS_END_SCENE_TYPE_COURSE_CLEAR_TIMING_START	100
#define WORDS_END_SCENE_TYPE_YOU_GOT_A_CARD_TIMING_START	700
#define WORDS_END_SCENE_TYPE_ITEM_TIMING_START				1300



//#============== WORLD MAP
#define TIME_PICKER_RESET_VALUE				300
#define	WORLD_MAP_NODE_PLAY_SCENE_1_1		2
#define WORLD_MAP_NODE_PLAY_SCENE_1_4		8


#define WORLD_MAP_OBJECT_TYPE_MARIO				0
#define WORLD_MAP_OBJECT_TYPE_HELP				1
#define WORLD_MAP_OBJECT_TYPE_GOLD_DIGGER			2
#define WORLD_MAP_OBJECT_TYPE_BUSH				3
#define WORLD_MAP_OBJECT_TYPE_NODE				4

#define WORLD_MAP_OBJECT_TYPE_HUD_PANEL			5
#define WORLD_MAP_OBJECT_TYPE_MARIO_LUIGI			6
#define WORLD_MAP_OBJECT_TYPE_LIFE				7
#define WORLD_MAP_OBJECT_TYPE_MONEY				8
#define WORLD_MAP_OBJECT_TYPE_SCORE				9
#define WORLD_MAP_OBJECT_TYPE_TIME_PICKER			10
#define WORLD_MAP_OBJECT_TYPE_WORLD				11
#define WORLD_MAP_OBJECT_TYPE_STACK_NORMAL		12
#define WORLD_MAP_OBJECT_TYPE_STACK_MAX			13
#define WORLD_MAP_OBJECT_TYPE_ITEM				14
#define WORLD_MAP_OBJECT_TYPE_STAGE_1				15
#define WORLD_MAP_OBJECT_TYPE_STAGE_2				16






//#=================== WORLD MAP OBJECTS
#define MARIO_STATE_MOVE_RIGHT		100
#define MARIO_STATE_MOVE_LEFT		200
#define MARIO_STATE_MOVE_UP			300
#define MARIO_STATE_MOVE_DOWN		400
#define MARIO_STATE_CANT_MOVE		500

#define GOLD_DIGGER_STATE_WALKING_RIGHT	600
#define GOLD_DIGGER_STATE_WALKING_LEFT	700

#define WORLD_MAP_TYPE_ANI_BUSH			0
#define WORLD_MAP_TYPE_ANI_HELP			1
#define WORLD_MAP_TYPE_ANI_GOLD_DIGGER_WALK_RIGHT	2
#define WORLD_MAP_TYPE_ANI_MARIO_SMALL		3
#define WORLD_MAP_TYPE_ANI_GOLD_DIGGER_WALK_LEFT	4
#define WORLD_MAP_TYPE_STAGE_CLEAR_ANI_IN_PROGRESS			5	
#define WORLD_MAP_TYPE_STAGE_CLEAR_ANI_FINISH		6
#define WORLD_MAP_TYPE_ANI_MARIO_BIG		7
#define WORLD_MAP_TYPE_ANI_MARIO_TAIL		8
#define WORLD_MAP_TYPE_ANI_MARIO_FIRE		9


#define WORLD_MAP_TYPE_MARIO		11
#define WORLD_MAP_TYPE_HELP			22
#define WORLD_MAP_TYPE_GOLD_DIGGER	33
#define WORLD_MAP_TYPE_BUSH			44
#define WORLD_MAP_TYPE_STAGE_1		55
#define WORLD_MAP_TYPE_STAGE_2		66
#define GOLD_DIGGER_WALK_START_TIMING	1500
#define HELP_APPEAR_START_TIMING		1000
#define WORLD_MAP_MARIO_MOVE_START		200
#define world_map_timing_clear_1		50
#define world_map_timing_clear_2		700
#define world_map_timing_clear_3		1500
#define MARIO_STATE_CANT_MOVE_SPEED		0
#define MARIO_STATE_MOVE_RIGHT_SPEED   0.22f
#define MARIO_STATE_MOVE_LEFT_SPEED		0.22f
#define MARIO_STATE_MOVE_UP_SPEED			0.22f
#define MARIO_STATE_MOVE_DOWN_SPEED			0.22f
#define GOLD_DIGGER_STATE_WALKING_RIGHT_SPEED	0.02f
#define GOLD_DIGGER_STATE_WALKING_LEFT_SPEED	0.02f



//#=============== BREAKABLE BRICK
#define BREAKABLE_BRICK_BBOX_WIDTH		16
#define BREAKABLE_BRICK_BBOX_HEIGHT		16

#define BREAKABLE_BRICK_STATE_NORMAL	0
#define BREAKABLE_BRICK_STATE_BREAK		100
#define BREAKABLE_BRICK_STATE_COIN		200
#define BREAKABLE_BRICK_STATE_SLIDING	300



#define BREAKABLE_BRICK_ANI_NORMAL		0
#define BREAKABLE_BRICK_ANI_COIN		1
#define BREAKABLE_BRICK_STATE_COIN_REVIVE_TIME		5000
#define BREAKABLE_BRICK_STATE_SLIDING_TIME_UPS		4
#define BREAKABLE_BRICK_STATE_SLIDING_BONUS_Y		2
#define BREAKABLE_BRICK_STATE_IDLE_SPEED			0



//#=============== BOOMERANG
#define BOOMERANG_BBOX_WIDTH  16
#define BOOMERANG_BBOX_HEIGHT 16

#define BOOMERANG_ANI_FLY_RIGHT		0
#define BOOMERANG_ANI_FLY_LEFT		1

#define BOOMERANG_SET_POSITION_X	8
#define BOOMERANG_SET_POSITION_Y	5
#define BOOMERANG_TIME_SWITCH_STATE_1	1000
#define BOOMERANG_TIME_SWITCH_STATE_2	50
#define BOOMERANG_TIME_SWITCH_STATE_3	250
#define BOOMERANG_TIME_SWITCH_STATE_4	1700
#define BOOMERANG_TIME_SWITCH_STATE_5	2400
#define BOOMERANG_TIME_SWITCH_STATE_6	5200
#define BOOMERANG_VX				0.1f
#define BOOMERANG_SET_ORIGIN_POSITION	33000
#define BOOMERANG_ORIGIN_SPEED			0
#define BOOMERANG_VY_1					0.00006f
#define BOOMERANG_VY_2					0.00015f



//BOOMERANG ENEMY
#define  BOOMERANG_ENEMY_LOOK_LEFT_LIMIT		-1
#define  BOOMERANG_ENEMY_LOOK_RIGTH_LIMIT		18
#define  BOOMERANG_ENEMY_BBOX_WIDTH		16
#define  BOOMERANG_ENEMY_BBOX_HEIGHT	24

#define  BOOMERANG_ENEMY_STATE_IDLE				0
#define  BOOMERANG_ENEMY_STATE_MOVE_FORWARD		100
#define  BOOMERANG_ENEMY_STATE_MOVE_BACKWARD    200
#define	 BOOMERANG_ENEMY_STATE_DIE				300

#define BOOMERANG_ENEMY_GRAVITY		0.002f

#define BOOMERANG_ENEMY_ANI_NORMAL_RIGHT				0
#define BOOMERANG_ENEMY_ANI_THROW_BOOMERANG_RIGHT		1
#define BOOMERANG_ENEMY_ANI_DIE_RIGHT					2
#define BOOMERANG_ENEMY_ANI_DIE_LEFT					3
#define BOOMERANG_ENEMY_ANI_NORMAL_LEFT					4	
#define BOOMERANG_ENEMY_ANI_THROW_BOOMERANG_LEFT		5
#define	RENDER_THROW_ANI_TIME_LIMIT		300
#define	RENDER_THROW_TIME_LIMIT		900
#define	RENDER_SECOND_THROW_TIME_LIMIT	3300
#define	BOOMETANG_ENEMY_STATE_MOVE_FORWARD_LIMIT	700
#define	BOOMETANG_ENEMY_STATE_IDLE_LIMIT	2000
#define	BOOMETANG_ENEMY_STATE_MOVE_BACKWARD_LIMIT	2700
#define	BOOMETANG_ENEMY_STATE_IDLE_2_LIMIT	4000
#define	BOOMETANG_ENEMY_VX	0.03f
#define	BOOMETANG_ENEMY_VY	0

class Define
{
public:
	Define();
	~Define();
};

